import { ObjectType } from "@/types/filtering";

export let objectInfo = {
  "2024 Total Solar Eclipse": {
    objectType: ObjectType.Eclipse,
    name: "2024 Total Solar Eclipse",
  },
  "2024 Penumbral Lunar Eclipse": {
    objectType: ObjectType.Eclipse,
    name: "2024 Penumbral Lunar Eclipse",
  },
  "2025 Total Lunar Eclipse": {
    objectType: ObjectType.Eclipse,
    name: "2025 Total Lunar Eclipse",
  },
  Moon: { objectType: ObjectType.Lunar, name: "Moon" },
  Sun: { objectType: ObjectType.Solar, name: "Sun" },
  Jupiter: { objectType: ObjectType.Planetary, name: "Jupiter" },
  M14: { objectType: ObjectType.StarCluster, name: "Globular Cluster" },
  M34: { objectType: ObjectType.StarCluster, name: "Spiral Cluster" },
  M35: { objectType: ObjectType.StarCluster, name: "Shoe-Buckle Cluster" },
  M37: { objectType: ObjectType.StarCluster, name: "Salt and Pepper Cluster" },
  M45: { objectType: ObjectType.StarCluster, name: "Pleiades Cluster" },
  M31: { objectType: ObjectType.Galaxy, name: "Andromeda Galaxy" },
  M33: { objectType: ObjectType.Galaxy, name: "Triangulum Galaxy" },
  "M66 Group": { objectType: ObjectType.Galaxy, name: "Leo Triplet" },
  M77: { objectType: ObjectType.Galaxy, name: "Squid Galaxy" },
  M94: { objectType: ObjectType.Galaxy, name: "Croc's Eye Galaxy" },
  M100: { objectType: ObjectType.Galaxy, name: "Grand Spiral Galaxy" },
  M104: { objectType: ObjectType.Galaxy, name: "Sombrero Galaxy" },
  NGC891: { objectType: ObjectType.Galaxy, name: "Silver Sliver Galaxy" },
  NGC2903: { objectType: ObjectType.Galaxy, name: "Spiral Galaxy" },
  M1: { objectType: ObjectType.Nebula, name: "Crab Nebula" },
  M16: { objectType: ObjectType.Nebula, name: "Eagle Nebula" },
  M17: { objectType: ObjectType.Nebula, name: "Omega Nebula" },
  M27: { objectType: ObjectType.Nebula, name: "Dumbbell Nebula" },
  M42: { objectType: ObjectType.Nebula, name: "Orion Nebula" },
  IC405: { objectType: ObjectType.Nebula, name: "Flaming Star Nebula" },
  IC410: { objectType: ObjectType.Nebula, name: "Tadpole Nebula" },
  IC434: { objectType: ObjectType.Nebula, name: "Horsehead Nebula" },
  IC443: { objectType: ObjectType.Nebula, name: "Jellyfish Nebula" },
  NGC1499: { objectType: ObjectType.Nebula, name: "California Nebula" },
  NGC1579: { objectType: ObjectType.Nebula, name: "Northern Trifid Nebula" },
  NGC2175: { objectType: ObjectType.Nebula, name: "Monkey Head Nebula" },
  NGC6960: { objectType: ObjectType.Nebula, name: "Western Veil Nebula" },
  "SH2-275": { objectType: ObjectType.Nebula, name: "Rosette Nebula" },
};
